dist: trusty

sudo: false

language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'

install:
    - composer update --prefer-dist --no-interaction

script:
    - vendor/bin/codecept run unit --coverage-xml
    - vendor/bin/coveralls

# cache vendor dirs
cache:
    directories:
        - $HOME/.composer/cache